In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [9]:
my_matrix=([1,2,3],[6,7,8],[2,4,5])

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [6, 7, 8],
       [2, 4, 5]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,2,20)

array([0])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros(1)

array([0.])

In [21]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.linspace(0,30,3)

array([ 0., 15., 30.])

In [26]:
np.linspace(1,40,4)

array([ 1., 14., 27., 40.])

In [27]:
np.linspace(1,6,25)

array([1.        , 1.20833333, 1.41666667, 1.625     , 1.83333333,
       2.04166667, 2.25      , 2.45833333, 2.66666667, 2.875     ,
       3.08333333, 3.29166667, 3.5       , 3.70833333, 3.91666667,
       4.125     , 4.33333333, 4.54166667, 4.75      , 4.95833333,
       5.16666667, 5.375     , 5.58333333, 5.79166667, 6.        ])

In [28]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.array(4)

array(4)

In [31]:
np.random.rand(1)

array([0.53159011])

In [32]:
np.random.rand(4)

array([0.11208317, 0.96292139, 0.49298612, 0.78906657])

In [33]:
np.random.rand(4,5)

array([[0.57704081, 0.52267508, 0.97047802, 0.72137026, 0.20482331],
       [0.62580802, 0.82383511, 0.49203352, 0.18346228, 0.62391231],
       [0.01284932, 0.85369268, 0.68076006, 0.08516143, 0.43190563],
       [0.9922532 , 0.71764701, 0.16606115, 0.89999828, 0.8055516 ]])

In [35]:
np.random.rand(2)

array([0.25721203, 0.84977596])

In [36]:
np.random.randint(3)

2

In [39]:
np.random.randint(4)

1

In [40]:
np.random.randint(1,20)

4

In [41]:
np.random.randint(1,100,2)

array([61, 87])

In [42]:
np.random.randint(1,100,10)

array([21, 46, 70, 57, 26, 70, 38,  4, 15,  6])

In [43]:
array=np.arange(25)

In [44]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr=np.random.randint(1,30,5)

In [46]:
ranarr

array([ 6, 24,  1, 25, 26])

In [48]:
ranarr.max()

26

In [49]:
ranarr.min()

1

In [50]:
ranarr.argmax()

4

In [51]:
ranarr.argmin()

2

In [57]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
arr=ranarr
arr.shape


(5,)

In [61]:
v=np.array([1,2,3])
print(v)

[1 2 3]


In [62]:
v.shape

(3,)

In [66]:
list(range(0,25))


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [67]:
print(list)

<class 'list'>


In [68]:
a=np.array([[2,3],[4,5],[6,7]])
a.shape


(3, 2)

In [71]:
b=np.array([[2,4,5],[6,7,8],['a','c','g']])
b.shape

(3, 3)

In [72]:
import numpy as np

In [77]:
arr=np.arange(0,11)


In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr[5]

5

In [80]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [81]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr[9:]

array([ 9, 10])

In [83]:
arr[-7:5]

array([4])

In [84]:
arr[0:5]=25

In [85]:
arr

array([25, 25, 25, 25, 25,  5,  6,  7,  8,  9, 10])

In [88]:
slice_of_arr=arr[0:6]

In [89]:
slice_of_arr

array([25, 25, 25, 25, 25,  5])

In [90]:
slice_of_arr=arr[1:5]

In [91]:
slice_of_arr

array([25, 25, 25, 25])

In [92]:
slice_of_arr[:]=99

In [93]:
slice_of_arr

array([99, 99, 99, 99])

In [94]:
slice_of_arr[1:]

array([99, 99, 99])

In [95]:
arr_2d=np.array([[4,5,6],[5,7,8],[8,4,5]])
arr_2d

array([[4, 5, 6],
       [5, 7, 8],
       [8, 4, 5]])

In [96]:
arr_2d[1]

array([5, 7, 8])

In [97]:
arr_2d[1][1]

7

In [98]:
arr_2d[0][1]

5

In [99]:
arr_2d[2][2]

5

In [100]:
arr_2d[:2]

array([[4, 5, 6],
       [5, 7, 8]])

In [101]:
arr_2d[2:]

array([[8, 4, 5]])

In [102]:
arr_2d[1]

array([5, 7, 8])

In [103]:
arr_2d[1][2]

8

In [104]:
arr2d=np.zeros((10,10))

In [105]:
arr_length=arr2d.shape[1]

In [106]:
for i in range (arr_length):
    arr2d[i]=i
    

In [107]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [108]:
arr2d=np.ones((10,10))

In [109]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [110]:
arr=np.arange(1,11)

In [111]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [112]:
bool_arr=arr>4

In [113]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [114]:
arr<2

array([ True, False, False, False, False, False, False, False, False,
       False])

In [115]:
x=2

In [116]:
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
arr>x

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])